- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: install Curl
      apt:
        pkg: "{{ item.name }}"
        state: present
      with_items:
      - { name: 'curl' }

    - name: Ensure that the path exist
      file: path=/opt/ssh-login-alert-telegram state=directory

    - name: Copy required files
      copy: src={{ item.src }} dest=/opt/ssh-login-alert-telegram/
      with_items:
        - { src: "{{ playbook_dir }}/ssh-login-alert-telegram/alert.sh", owner: root, group: root, mode: 0755 }
        - { src: "{{ playbook_dir }}/credentials.config", owner: root, group: root, mode: 0755  }

    - name: Deploy the alerting
      script: "{{ playbook_dir }}/ssh-login-alert-telegram/deploy.sh"
